In [1]:
a = [1,2,3]

In [2]:
a[0:2]

[1, 2]

In [4]:
import numpy

In [12]:
a= numpy.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
b =a.reshape(3,3)

In [14]:
a[0:2]

array([0, 1])

In [18]:
a[0:2,1:2]

IndexError: too many indices for array

In [21]:
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
b[2:2]

array([], shape=(0, 3), dtype=int64)

In [23]:
b[0:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
b[0:1]

array([[0, 1, 2]])

In [25]:
b[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
b[0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
b[0:1,1:2]

array([[1]])

In [28]:
b[1:2,1:2]

array([[4]])

In [29]:
b[2:3,2:3]

array([[8]])

In [30]:
b.shape

(3, 3)

In [32]:
b[2,2]

8

In [33]:
for i in b:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [34]:
for y in b.T:
    print(y)

[0 3 6]
[1 4 7]
[2 5 8]


In [35]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
for x in b.flat:
    print(x)

0
1
2
3
4
5
6
7
8
