In [2]:
[[123,123,23,12,33],[],[]]

[[123, 123, 23, 12, 33], [], []]

In [10]:
import numpy
n= numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [11]:
type(n)

numpy.ndarray

In [12]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [13]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [14]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
m=numpy.asarray([[123,123,23,12,33],[],[]])
print(m)

[list([123, 123, 23, 12, 33]) list([]) list([])]


In [16]:
m

array([list([123, 123, 23, 12, 33]), list([]), list([])], dtype=object)

In [17]:
type(m)

numpy.ndarray