In [1]:
import numpy
a = numpy.arange(27)
b = a.reshape(3,9)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [2]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
ims = numpy.hstack((b,b))
ims

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  0,  1,  2,  3,  4,  5,  6,
         7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 18, 19, 20, 21, 22, 23, 24,
        25, 26]])

In [7]:
print(ims)

[[ 0  1  2  3  4  5  6  7  8  0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 18 19 20 21 22 23 24 25 26]]


In [8]:
ims = numpy.vstack((b,b))

In [9]:
ims

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [14]:
lst = numpy.vsplit(ims,3)
lst

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [15]:
lst = numpy.hsplit(ims,3)
lst

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20],
        [ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23],
        [ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26],
        [ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]])]

In [16]:
type(lst)

list

In [17]:
lst[0]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])